### ISSUE TITLE
Cannot install coq-json and coq-io-system with Coq 8.13.2 docker image

### ISSUE THREAD

**Issue by jjhugues** [coq-io/system-ocaml#5]
Hi,

Consider this minimal dockerfile as an example 

```
FROM coqorg/coq:8.13.2
RUN opam repo add coq-released --all-switches https://coq.inria.fr/opam/released && \
    opam repo add coq-extra-dev --all-switches https://coq.inria.fr/opam/extra-dev && \
    opam install -y  coq-io coq-json coq-io-system
```

The installation cannot complete

```
 > [2/2] RUN opam repo add coq-released --all-switches https://coq.inria.fr/opam/released &&     opam repo add coq-extra-dev --all-switches https://coq.inria.fr/opam/extra-dev &&     opam install -y  coq-io coq-json coq-io-system:          
#5 2.562 [coq-released] synchronised from https://coq.inria.fr/opam/released    
#5 3.816 [coq-extra-dev] Initialised                                            
#5 7.759 The following dependencies couldn't be met:
#5 7.759   - coq-json -> menhir >= 20210310 -> dune >= 2.2.0 -> ocamlfind-secondary -> ocaml-secondary-compiler
#5 7.759   - coq-io-system -> coq < 8.5~
#5 7.759       not available because the package is pinned to version 8.13.2
#5 7.759   - coq-io-system -> coq-io-system-ocaml
#5 7.759 Your request can't be satisfied:
#5 7.759   - coq-io-system-ocaml is in conflict with ocaml-secondary-compiler
#5 7.759 
#5 7.759 No solution found, exiting
```

The conflict seems to come from this patch:  https://github.com/coq/opam-coq-archive/commit/240ff1c284df6ecae80ba269f0a9d226f2c29170

Do you have a work-around to suggest? Can we weaken the conflict?
Thanks

**Comment by clarus** [comment]
Hello,

I am looking at it. For opam, there is the option `--ignore-constraints-on=`, does the following works?
```sh
opam install -y  coq-io coq-json coq-io-system --ignore-constraints-on=ocaml-secondary-compiler
```

**Comment by clarus** [comment]
After doing some tests the `--ignore-constraints-on=` option does not work. I think an issue with the Docker image `coqorg/coq:8.13.2` is that only the `4.05` and `4.07` versions of OCaml are available. These are quite old. I am asking for an update.

**Comment by clarus** [comment]
OK, so your example works using the Docker image `coqorg/coq:8.13-ocaml-4.11-flambda`. I asked the question about the default OCaml version for the Docker images here: https://github.com/coq-community/docker-coq/issues/30

**Comment by jjhugues** [comment]
Thanks for the detailed answer. I confirm this works.

**Comment by clarus** [comment]
OK cool!
